#!/bin/sh

ENGINE_OPTION=">> CHANGE ENGINE"
PROGRAM_OPTION=">> CHANGE PROGRAM"
CLIP_OPTION="$(xclip -selection c -o | tr '\n' ' ')"

ENGINE_CHOICES=$(tsearch -l engine)
PROGRAM_CHOICES=$(tsearch -l program)

PROMPT=$(tsearch -l default.engine)
COMMAND=tsearch
IS_SPECIAL_INPUT=1

if [ -n "$1" ]; then
    PROMPT=$1
    ENGINE=$1
    COMMAND="$COMMAND -e $ENGINE"
fi

main(){
    while [ $IS_SPECIAL_INPUT = 1 ]; do
        TERM=$(printf '%s\n%s\n%s' "$CLIP_OPTION" "$ENGINE_OPTION" "$PROGRAM_OPTION" | dmenu -p "$PROMPT:" -i)
        case "$TERM" in
            "$ENGINE_OPTION")
                SELECTED_ENGINE=$(printf '%s' "$ENGINE_CHOICES" | dmenu -p "Engine:" -i -l 10)
                if [ -n "$SELECTED_ENGINE" ]; then
                    ENGINE="$SELECTED_ENGINE"
                    PROMPT="$ENGINE"
                    COMMAND="$COMMAND -e $ENGINE"
                fi
                IS_SPECIAL_INPUT=1
            ;;
            "$PROGRAM_OPTION")
                SELECTED_PROGRAM=$(printf '%s' "$PROGRAM_CHOICES" | dmenu -p "Program:" -i)
                if [ -n "$SELECTED_PROGRAM" ]; then
                    PROGRAM="$SELECTED_PROGRAM"
                    COMMAND="$COMMAND -p $PROGRAM"
                fi
                IS_SPECIAL_INPUT=1
            ;;
            *)
                IS_SPECIAL_INPUT=0
            ;;
        esac
    done
    if [ -n "$TERM" ]; then
        $COMMAND -t "$TERM"
    fi
}

main